# Generated by Django 3.1.6 on 2021-02-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210222_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='Keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
