# Generated by Django 3.1.6 on 2021-02-28 16:12

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogpost_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
