# Generated by Django 3.1.6 on 2021-02-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explanation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explanation',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
