# Generated by Django 3.1.6 on 2021-02-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=256)),
                ('youtube_link', models.CharField(max_length=256)),
                ('video_code', models.CharField(max_length=256)),
                ('date', models.DateField()),
            ],
        ),
    ]
